### ISSUE TITLE
Lands support

### ISSUE THREAD

**Issue by eDexiam** [Ste3et/ProtectionLib#11]
Add support for [Lands](https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-nations-wars-1-18-support.53313/)

It is a paid plugin but the API is available [here for free](https://github.com/Angeschossen/LandsAPI)

**Comment by Ste3et** [comment]
the support for lands is already includet https://github.com/Ste3et/ProtectionLib/blob/master/Core/src/main/java/de/Ste3et_C0st/ProtectionLib/main/plugins/fLands.java please check /protectionlib plugins if he corrected hook into it!

**Comment by eDexiam** [comment]
Oops, my bad, it wasn't written on the spigot page so I assumed it wasn't supported, thanks 👍
