### ISSUE TITLE
[suggestion]GriefDefender Support

### ISSUE THREAD

**Issue by hkkongou** [Ste3et/ProtectionLib#6]
ProtectionLib support a lot of claim plugins, but does not support griefdefender, players can place furniture inside griefdefender claims without any prevention.

Please add Griefdefender support so that players cannot place furniture in places does not belongs to them. Thank you.

* Griefdefender is not same as griefprevention

**Comment by Ste3et** [comment]
Please try that devbuild of ProtectionLIb and give feedback of it.

https://dicecraft.de/furniture/download.php?plugin=ProtectionLib&build=DevBuild&version=Spigot%201.9.x%20-%201.17.x&buildNummer=325238828

**Comment by hkkongou** [comment]
> Please try that devbuild of ProtectionLIb and give feedback of it.
> 
> https://dicecraft.de/furniture/download.php?plugin=ProtectionLib&build=DevBuild&version=Spigot%201.9.x%20-%201.17.x&buildNummer=325238828

it work great, thank you so much
but is it possible to show an extra message when the place event is cancelled?

**Comment by Ste3et** [comment]
Id think that the ProtectionLib is not the right spot to implement some message stuff.
Please open a suggestion in the FurnitureLib repo
