### ISSUE TITLE
Support Plotsquared 6

### ISSUE THREAD

**Issue by Malachiel87** [Ste3et/ProtectionLib#7]
Hi, plotsquared 6 has been recently added and since the api is changed the protectionlib don't find it
```
[05:01:40 INFO]: [ProtectionLib] Enabling ProtectionLib v1.1
[05:01:40 INFO]: [ProtectionLib] Protection lib hook into: PlotSquared 6.0.0-Premium
[05:01:40 ERROR]: [ProtectionLib] Plugin ProtectionLib v1.1 has failed to register events for class de.Ste3et_C0st.ProtectionLib.main.plugins.fPlotSquared because com/github/intellectualsites/plotsquared/bukkit/events/PlotClearEvent does not exist.
```

Can you kindy update? Thank you :)

**Comment by Ste3et** [comment]
Please try that devbuild of ProtectionLIb and give feedback of it.
It looks like Plotsqauredv6 use the same API as v5

https://dicecraft.de/furniture/download.php?plugin=ProtectionLib&build=DevBuild&version=Spigot%201.9.x%20-%201.17.x&buildNummer=325238828

**Comment by Malachiel87** [comment]
just tested right now, is not working

> [16:19:13 INFO]: [ProtectionLib] Enabling ProtectionLib v1.2-dev-372ad211
> [16:19:13 INFO]: [ProtectionLib] Protection lib hook into: PlotSquared 6.0.0-Premium
> [16:19:13 ERROR]: Error occurred while enabling ProtectionLib v1.2-dev-372ad211 (Is it up to date?)
> java.lang.NoClassDefFoundError: com/plotsquared/core/api/PlotAPI
>         at de.Ste3et_C0st.ProtectionLib.main.plugins.fPlotsquaredV5.<init>(fPlotsquaredV5.java:27) ~[?:?]
>         at de.Ste3et_C0st.ProtectionLib.main.ProtectionLib.addProtectionPlugin(ProtectionLib.java:116) ~[?:?]
>         at de.Ste3et_C0st.ProtectionLib.main.ProtectionLib.addWatchers(ProtectionLib.java:78) ~[?:?]
>         at de.Ste3et_C0st.ProtectionLib.main.ProtectionLib.onEnable(ProtectionLib.java:66) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at java.lang.Thread.run(Thread.java:831) [?:?]
> Caused by: java.lang.ClassNotFoundException: com.plotsquared.core.api.PlotAPI
>         at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-"a9394b8"]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
>         ... 14 more
> [16:19:13 INFO]: [ProtectionLib] Disabling ProtectionLib v1.2-dev-372ad211

It will just disable itself at startup

**Comment by Ste3et** [comment]
Sorry then is official api docs arn't corrlecty updated

**Comment by Malachiel87** [comment]
Try looking here https://ci.athion.net/job/PlotSquared-v6-Javadocs/ and https://github.com/IntellectualSites/PlotSquared

**Comment by Ste3et** [comment]
One of the biggest problems is that the ProtectionLib didn't have a maven parent/child system, if i want to support PlotSqaured v5 & v6 i should swap to another system but i din't have the time to do it.

**Comment by Malachiel87** [comment]
take your time :)

**Comment by Ste3et** [comment]
Thats the problem i didn't have time.
I have 48h before i need to fly to Helsinki to work in a powerplant, if i didn't can push the update before the plugin can't updatet for the next 10 weks because i must work every day 11houres and have only one day weekand every 2 weeks.

**Comment by Malachiel87** [comment]
Don't worry i can wait

**Comment by Ste3et** [comment]
After spending hours over hours and a lots of rework i must stop for today!
I hope that the thing works for later (sad life ...) [i hate to switch to another thing]

**Comment by Ste3et** [comment]
Ok now the Project is switched to Maven Modules, after Hours of research and testing i found that way to compile my whole code you can find the artifact here: https://dicecraft.de/furniture/download.php?plugin=ProtectionLib&build=DevBuild&version=Spigot%201.9.x%20-%201.17.x&buildNummer=325797512
Sorry for the slow response, it takes 13 houres for me as maven noob to switch to a stable build

**Comment by Malachiel87** [comment]
it seem to work and hook correct now, you are the amazing and best dev  :)

[11:25:33 INFO]: [ProtectionLib] Enabling ProtectionLib v1.2-dev-de70ac28
[11:25:33 INFO]: ProtectionLib-Module: LocalLibary hooked!
[11:25:33 INFO]: ProtectionLib-Module: PlotSquaredV5Module hooked!
[11:25:33 INFO]: ProtectionLib-Module: PlotSquaredV6Module hooked!
[11:25:33 INFO]: Protection lib hook into: PlotSquared 6.0.0-Premium
[11:25:33 INFO]: Protection lib hook into: PlotSquared 6.0.0-Premium
